//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.HeadOfProgramme
{
    public partial class HOPAnnouncements
    {
        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// litSuccessMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSuccessMsg;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litErrorMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorMsg;

        /// <summary>
        /// ddlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        /// <summary>
        /// ddlAudience control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAudience;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtBody control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBody;

        /// <summary>
        /// txtExpiryDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExpiryDays;

        /// <summary>
        /// btnPublish control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPublish;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;


        /// <summary>
        /// txtFilterTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterTitle;

        /// <summary>
        /// ddlFilterAuthor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterAuthor;

        /// <summary>
        /// ddlFilterCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterCourse;

        /// <summary>
        /// txtFilterPostedDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterPostedDate;

        /// <summary>
        /// txtFilterExpiryDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterExpiryDate;

        /// <summary>
        /// btnApplyFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilter;

        /// <summary>
        /// btnClearFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearFilter;
        /// <summary>
        /// rptAnnouncements control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAnnouncements;

        /// <summary>
        /// pnlNoAnnouncements control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAnnouncements;
    }
}
