//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.HeadOfProgramme
{
    public partial class HOPArchivedEnrolments
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtSearchStudent;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterCourse;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblArchivedCount;
        protected global::System.Web.UI.WebControls.Button btnExportArchived;
        protected global::System.Web.UI.WebControls.Button btnRestoreSelected;
        protected global::System.Web.UI.WebControls.GridView gvArchived;
    }
}
