//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.HeadOfProgramme
{
    public partial class Dashboard
    {
        /// <summary>
        /// litProgrammesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProgrammesCount;

        /// <summary>
        /// litCoursesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCoursesCount;

        /// <summary>
        /// litStudentsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStudentsCount;

        /// <summary>
        /// litLecturersCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLecturersCount;
    }
}
