//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.HeadOfProgramme
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Content Head;
        protected global::System.Web.UI.WebControls.Content Main;

        protected global::System.Web.UI.WebControls.HiddenField hfProgrammeLabelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfProgrammeDataJson;
        protected global::System.Web.UI.WebControls.HiddenField hfStatusLabelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfStatusDataJson;
        protected global::System.Web.UI.WebControls.HiddenField hfAttendanceLabelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfAttendanceDataJson;
        protected global::System.Web.UI.WebControls.HiddenField hfPerformanceLabelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfPerformanceDataJson;

        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;
        protected global::System.Web.UI.WebControls.LinkButton btnApplyFilter;

        protected global::System.Web.UI.WebControls.Literal litProgrammesCount;
        protected global::System.Web.UI.WebControls.Literal litCoursesCount;
        protected global::System.Web.UI.WebControls.Literal litStudentsCount;
        protected global::System.Web.UI.WebControls.Literal litLecturersCount;
        protected global::System.Web.UI.WebControls.Literal litEnrolmentsCount;
        protected global::System.Web.UI.WebControls.Literal litActiveStudentsCount;
        protected global::System.Web.UI.WebControls.Literal litStudentsAtRisk;
        protected global::System.Web.UI.WebControls.Literal litAttendanceRate;
        protected global::System.Web.UI.WebControls.Literal litAveragePerformance;

        protected global::System.Web.UI.WebControls.Panel pnlAttendanceNote;
        protected global::System.Web.UI.WebControls.Panel pnlPerformanceNote;

        protected global::System.Web.UI.WebControls.LinkButton btnEnrolmentReport;
        protected global::System.Web.UI.WebControls.LinkButton btnPerformanceReport;
        protected global::System.Web.UI.WebControls.LinkButton btnAttendanceReport;

        protected global::System.Web.UI.WebControls.GridView gvProgrammeReport;
        protected global::System.Web.UI.WebControls.Literal litGeneratedReportTitle;
        protected global::System.Web.UI.WebControls.Label litGeneratedReportMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlExportFormat;
        protected global::System.Web.UI.WebControls.LinkButton btnExportReport;
        protected global::System.Web.UI.WebControls.Label lblExportMessage;
        protected global::System.Web.UI.WebControls.GridView gvGeneratedReport;
    }
}
