//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.HeadOfProgramme
{
    public partial class HOPManageEnrolments
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtSearchStudent;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterRequestType;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblPendingCount;
        protected global::System.Web.UI.WebControls.GridView gvPending;
        protected global::System.Web.UI.WebControls.Label lblApprovedCount;
        protected global::System.Web.UI.WebControls.HyperLink lnkArchivedEnrolments;
        protected global::System.Web.UI.WebControls.Button btnArchiveSelected;
        protected global::System.Web.UI.WebControls.GridView gvApproved;
        protected global::System.Web.UI.WebControls.Label lblRejectedCount;
        protected global::System.Web.UI.WebControls.Button btnDeleteSelected;
        protected global::System.Web.UI.WebControls.GridView gvRejected;
    }
}
