//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.HeadOfProgramme
{
    public partial class HOPManageAdmissions
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlApplicantDetails;
        protected global::System.Web.UI.WebControls.Button btnCloseDetails;
        protected global::System.Web.UI.WebControls.Label lblDetailFullName;
        protected global::System.Web.UI.WebControls.Label lblDetailEmail;
        protected global::System.Web.UI.WebControls.Label lblDetailPhone;
        protected global::System.Web.UI.WebControls.Label lblDetailDOB;
        protected global::System.Web.UI.WebControls.Label lblDetailGender;
        protected global::System.Web.UI.WebControls.Label lblDetailNationalId;
        protected global::System.Web.UI.WebControls.Label lblDetailNationality;
        protected global::System.Web.UI.WebControls.Label lblDetailPreviousInstitution;
        protected global::System.Web.UI.WebControls.Label lblDetailHighestQualification;
        protected global::System.Web.UI.WebControls.Label lblDetailPreviousCGPA;
        protected global::System.Web.UI.WebControls.Label lblDetailProgramme;
        protected global::System.Web.UI.WebControls.Label lblDetailIntake;
        protected global::System.Web.UI.WebControls.Label lblDetailStatus;
        protected global::System.Web.UI.WebControls.Label lblDetailRequestedAt;
        protected global::System.Web.UI.WebControls.Label lblDetailRejectionReason;
        protected global::System.Web.UI.WebControls.TextBox txtSearchStudent;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterProgramme;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblPendingCount;
        protected global::System.Web.UI.WebControls.GridView gvPending;
        protected global::System.Web.UI.WebControls.Label lblApprovedCount;
        protected global::System.Web.UI.WebControls.Button btnArchiveSelectedApproved;
        protected global::System.Web.UI.WebControls.Button btnExportAdmitted;
        protected global::System.Web.UI.WebControls.Button btnDeleteSelectedRejected;
        protected global::System.Web.UI.WebControls.Button btnExportRejected;
        protected global::System.Web.UI.WebControls.GridView gvApproved;
        protected global::System.Web.UI.WebControls.Label lblRejectedCount;
        protected global::System.Web.UI.WebControls.GridView gvRejected;
    }
}
